### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by BenLubar** [boomzillawtf/nodebb-plugin-youtube-embed#5]
6/7 22:47:51 [1041] - error: [4572/1041]  SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at /usr/src/app/node_modules/nodebb-plugin-youtube-embed/library.js:81:31
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/nodebb-plugin-youtube-embed/library.js:58:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by exomarty** [comment]
same problem here

**Comment by barisusakli** [comment]
https://github.com/boomzillawtf/nodebb-plugin-youtube-embed/pull/7
