### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined (snippet.channelTitle missing)

### ISSUE THREAD

**Issue by BenLubar** [boomzillawtf/nodebb-plugin-youtube-embed#8]
```
2018-03-18T14:58:39.151Z [21281] - error: [4568/21281]  TypeError: Cannot read property 'split' of undefined
    at replaceAll (/usr/src/app/plugins/nodebb-plugin-youtube-embed/library.js:138:17)
    at /usr/src/app/plugins/nodebb-plugin-youtube-embed/library.js:96:40
    at IncomingMessage.<anonymous> (/usr/src/app/plugins/nodebb-plugin-youtube-embed/library.js:58:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Post in question:

```json
{
        "_id" : ObjectId("56de7673f848f35aae03713b"),
        "_key" : "post:632167",
        "pid" : 632167,
        "uid" : 876,
        "tid" : 16725,
        "content" : "The other sad thing is that people continue to feed bears and other wildlife despite many signs in the parks, and fines.  Usually they do this from their car though, so sadly Darwin won't kick in for them and some other unlucky visitors are likely to suffer the consequences.\n\nLocal officials here just put out another public notice yesterday asking visitors to report anyone seen feeding wildlife.\n\nhttps://www.youtube.com/watch?v=ol5kIHKr2fk",
        "timestamp" : 1437759894647,
        "votes" : 0,
        "editor" : "",
        "edited" : 1437759894647,
        "deleted" : 0,
        "_imported_pid" : 977669,
        "_imported_uid" : 975,
        "_imported_tid" : 100379,
        "_imported_content" : "The other sad thing is that people continue to feed bears and other wildlife despite many signs in the parks, and fines.  Usually they do this from their car though, so sadly Darwin won't kick in for them and some other unlucky visitors are likely to suffer the consequences.\n\nLocal officials here just put out another public notice yesterday asking visitors to report anyone seen feeding wildlife.\n\nhttps://www.youtube.com/watch?v=ol5kIHKr2fk",
        "_imported_cid" : 10,
        "_imported_ip" : "",
        "_imported_guest" : "",
        "_imported_toPid" : "",
        "_imported_user_slug" : "",
        "_imported_user_path" : "/users/quijibo",
        "_imported_topic_slug" : "",
        "_imported_topic_path" : "",
        "_imported_category_path" : "/c/side-bar-wtf",
        "_imported_category_slug" : "side-bar-wtf",
        "_imported_path" : "",
        "bookmarks" : 2
}
```

YouTube API output:

```json
{
 "items": [
  {
   "snippet": {
    "title": "Parks Canada video: People feeding bears in Banff fined",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/ol5kIHKr2fk/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/ol5kIHKr2fk/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/ol5kIHKr2fk/hqdefault.jpg",
      "width": 480,
      "height": 360
     },
     "standard": {
      "url": "https://i.ytimg.com/vi/ol5kIHKr2fk/sddefault.jpg",
      "width": 640,
      "height": 480
     },
     "maxres": {
      "url": "https://i.ytimg.com/vi/ol5kIHKr2fk/maxresdefault.jpg",
      "width": 1280,
      "height": 720
     }
    }
   },
   "contentDetails": {
    "duration": "PT19S"
   }
  }
 ]
}
```

**Comment by Tsaukpaetra** [comment]
https://www.youtube.com/watch?v=ol5kIHKr2fk
This video is unavailable... But I still have images from it :confused:
